project_name: dogechain

release:
  disable: false
  draft: true
  prerelease: auto

builds:
  - id: darwin-amd64
    main: ./main.go
    binary: dogechain
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    ldflags: >
      -s -w
      -X 'github.com/dogechain-lab/dogechain/versioning.Version=v{{ .Version }}
      -X 'github.com/dogechain-lab/dogechain/versioning.Commit={{ .GITHUB_COMMIT_HASH }}'
      -X 'github.com/dogechain-lab/dogechain/versioning.BuildTime={{ .GITHUB_BUILT_AT }}'
    tags:
      - osusergo
      - netgo
      - static_build

  - id: darwin-arm64
    main: ./main.go
    binary: dogechain
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    ldflags: >
      -s -w
      -X 'github.com/dogechain-lab/dogechain/versioning.Version=v{{ .Version }}
      -X 'github.com/dogechain-lab/dogechain/versioning.Commit={{ .GITHUB_COMMIT_HASH }}'
      -X 'github.com/dogechain-lab/dogechain/versioning.BuildTime={{ .GITHUB_BUILT_AT }}'
    tags:
      - osusergo
      - netgo
      - static_build

  - id: linux-amd64
    main: ./main.go
    binary: dogechain
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    # We need to build a static binary because we are building in a glibc based system and running in a musl container
    ldflags: >
      -s -w
      -X 'github.com/dogechain-lab/dogechain/versioning.Version=v{{ .Version }}
      -X 'github.com/dogechain-lab/dogechain/versioning.Commit={{ .GITHUB_COMMIT_HASH }}'
      -X 'github.com/dogechain-lab/dogechain/versioning.BuildTime={{ .GITHUB_BUILT_AT }}'
      -extldflags "-Wl,-z,stack-size=0x800000" "-static"
    tags:
      - osusergo
      - netgo
      - static_build

  - id: linux-arm64
    main: ./main.go
    binary: dogechain
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags: >
      -s -w
      -X 'github.com/dogechain-lab/dogechain/versioning.Version=v{{ .Version }}
      -X 'github.com/dogechain-lab/dogechain/versioning.Commit={{ .GITHUB_COMMIT_HASH }}'
      -X 'github.com/dogechain-lab/dogechain/versioning.BuildTime={{ .GITHUB_BUILT_AT }}'
      -extldflags "-Wl,-z,stack-size=0x800000" "-static"
    tags:
      - osusergo
      - netgo
      - static_build

archives:
  - files:
      - LICENSE
      - README.md
      - src: mainnet-genesis.json
        dst: genesis.json

snapshot:
  name_template: "{{ .Tag }}.next"

dockers:
  - image_templates:
      - dogechainlab/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile.release
    use: buildx
    goarch: amd64
    ids:
      - linux-amd64
    build_flag_templates:
      - --platform=linux/amd64
    skip_push: false

  - image_templates:
      - dogechainlab/{{ .ProjectName }}:{{ .Version }}-arm64
    dockerfile: Dockerfile.release
    use: buildx
    goarch: arm64
    ids:
      - linux-arm64
    build_flag_templates:
      - --platform=linux/arm64
    skip_push: false

docker_manifests:
  - name_template: dogechainlab/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - dogechainlab/{{ .ProjectName }}:{{ .Version }}-amd64
      - dogechainlab/{{ .ProjectName }}:{{ .Version }}-arm64
    skip_push: false

  - name_template: dogechainlab/{{ .ProjectName }}:latest
    image_templates:
      - dogechainlab/{{ .ProjectName }}:{{ .Version }}-amd64
      - dogechainlab/{{ .ProjectName }}:{{ .Version }}-arm64
    skip_push: false
