---
name: QA
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17.x"

      - name: Lint
        uses: golangci/golangci-lint-action@v3

  build:
    name: Build Test
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17.x"

      - run: |
          go build -a -o dogechain -ldflags="\
            -X 'github.com/dogechain-lab/dogechain/versioning.Version=${GITHUB_REF_NAME}' \
            -X 'github.com/dogechain-lab/dogechain/versioning.Commit=${GITHUB_COMMIT_HASH}' \
            -X 'github.com/dogechain-lab/dogechain/versioning.BuildTime=${GITHUB_BUILT_AT}' \
            -extldflags '"-Wl,-z,stack-size=0x800000" "-static"' "\
            -tags 'osusergo netgo static_build' && tar -czvf dogechain.tar.gz dogechain
        env:
          CGO_ENABLED: 0
          CC: gcc
          CXX: g++
          GOARC: amd64
          GOOS: linux
          GITHUB_COMMIT_HASH: ${{ github.sha }}
          GITHUB_BUILT_AT: ${{ github.event.head_commit.timestamp }}

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17.x"

      - name: Run Go Test
        run: go test -coverprofile coverage.out -timeout 20m `go list ./... | grep -v e2e`

      - name: Upload coverage file to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out

  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.x"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run tests
        run: make test-e2e
