name: Delete old workflow runs
on:
  schedule:
    # Run weekly, at 00:00 on every Monday.
    - cron: "0 0 * * 1"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "45 days" # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          # Optional inputs
          skip-tags: true
          skip-recent: 30
