name: Release

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*.*"
      # to be used by fork patch-releases ^^
      - "v*.*.*-*"

env:
  GO_VERSION: "1.19"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/actions/checkout/issues/1169
      - name: Workaround Git Security Warning
        run: |
          # Workaround a bug in github actions:
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=tag_name::${TAG}

      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION }}"

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64,darwin/amd64,darwin/arm64

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist --clean
        env:
          CGO_ENABLED: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: github.actor == 'abrahamcruise321' || github.actor == 'DarianShawn'
